FROM percona:latest
ARG MYSQL_DATABASE=hibp_local
ARG MYSQL_USER=hibp
ARG MYSQL_PASSWORD=password

ENV MYSQL_RANDOM_ROOT_PASSWORD yes
ENV MYSQL_DATABASE ${MYSQL_DATABASE}
ENV MYSQL_USER ${MYSQL_USER}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}

COPY --chown=mysql:mysql import.sql /var/lib/mysql-files/import.sql

EXPOSE 3306
