version: "2"

services:
  percona:
    image: percona/percona-server:latest
    container_name: "hibp_percona"
    command:
      - "--user=mysql"
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  hibp_node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    links:
      - percona:percona
    volumes:
      - node:/app


volumes:
  db:
    driver: local
  node:
    driver: local
